### ISSUE TITLE
Support for tidyr v1.0+

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/scipiper#122]
Not sure if there are other issues w/ the new `tidyr`, but I run into this one:
```r
scipiper::gd_confirm_posted('1_crosswalk_fetch/out/wbic_lakes_sf.rds.ind')
Error in as_tibble.dribble(output, .name_repair = "minimal") : 
  unused argument (.name_repair = "minimal")
```

Was fine when I rolled back w/ 
```r
devtools::install_github('tidyverse/tidyr@v0.8.0') 
```
looks like v0.8.3 or so introduced this deprecated arg?

**Comment by lindsayplatt** [comment]
I was also getting this error when trying to do `scmake(remake_file = "2_crosswalk_munge.yml")` from https://github.com/USGS-R/lake-temperature-model-prep. The issue wasn't with `tidyr`, though; it was actually with `googledrive`. You need a version > 1.0.0. There hasn't been a release since then, but [Jenny Bryan committed the change in Oct 2019 to fix it](https://github.com/tidyverse/googledrive/commit/66784505f4210ad2b8033676eed9b28c75a2d165), so I just installed the master branch with `devtools::install_github("tidyverse/googledrive")`. Tried using this and my build hasn't failed yet and usually it would have by now 🤞

**Comment by aappling-usgs** [comment]
This just saved me a second time - thanks, @lindsayplatt !
